#!/usr/bin/env python
# -*- coding: utf-8 -*-
#
#     rce-core/rce-rosproxy
#
#     This file is part of the RoboEarth Cloud Engine framework.
#
#     This file was originally created for RoboEearth
#     http://www.roboearth.org/
#
#     The research leading to these results has received funding from
#     the European Union Seventh Framework Programme FP7/2007-2013 under
#     grant agreement no248942 RoboEarth.
#
#     Copyright 2013 RoboEarth
#
#     Licensed under the Apache License, Version 2.0 (the "License");
#     you may not use this file except in compliance with the License.
#     You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
#     Unless required by applicable law or agreed to in writing, software
#     distributed under the License is distributed on an "AS IS" BASIS,
#     WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#     See the License for the specific language governing permissions and
#     limitations under the License.
#
#     \author/s: Mayank Singh
#
#

# twisted specific imports
from twisted.internet import reactor

# rce specific imports
from rce.rosproxy import main


def _get_argparse():
    from argparse import ArgumentParser

    parser = ArgumentParser(prog='rce-rosproxy',
                            description='RCE ROS proxy Process.')

    parser.add_argument('proxyPort', type=int,
                        help='Port where the HTTP server is listening for '
                             'requests.')

    return parser


if __name__ == '__main__':
    args = _get_argparse().parse_args()
    main(reactor, args.proxyPort)
