#!/bin/bash
# -*- coding: utf-8 -*-
#
#     rce-core/rce-make
#
#     This file is part of the RoboEarth Cloud Engine framework.
#
#     This file was originally created for RoboEearth
#     http://www.roboearth.org/
#
#     The research leading to these results has received funding from
#     the European Union Seventh Framework Programme FP7/2007-2013 under
#     grant agreement no248942 RoboEarth.
#
#     Copyright 2012 RoboEarth
#
#     Licensed under the Apache License, Version 2.0 (the "License");
#     you may not use this file except in compliance with the License.
#     You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
#     Unless required by applicable law or agreed to in writing, software
#     distributed under the License is distributed on an "AS IS" BASIS,
#     WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#     See the License for the specific language governing permissions and
#     limitations under the License.
#
#     \author/s: Dominique Hunziker
#
#

# Check if the script is run as super-user
if [ $(id -u) -ne 0 ]; then
    echo "rcemake has to be run as super-user."
    exit
fi

# Setup the container filesystem
RESULT=$(rce-setup-rcemake up)

if [ $? -ne 0 ]; then
    echo "Could not setup the rce environment."
    echo $RESULT
    exit
fi

# Setup HOME environment variable
TMP_HOME=$HOME
export HOME=/root

# Enter the container filesystem
chroot $RESULT /bin/bash

# restore environment variables
export HOME=$TMP_HOME

# Tear down the container filesystem
rce-setup-rcemake down
